# syntax=docker/dockerfile:1
FROM python:3.9.4-slim
WORKDIR /aiven
COPY ./requirements.txt requirements.txt
COPY ./website_checker website_checker/
RUN pip install --upgrade pip setuptools
RUN pip install -r requirements.txt
ENTRYPOINT ["python", "website_checker/producer.py"]